### ISSUE TITLE
Am I too fast?

### ISSUE THREAD

**Issue by djc** [actions-rs/tarpaulin#2]
https://github.com/djc/quinn/pull/597/checks?check_run_id=386985153

**Comment by svartalf** [comment]
Yeah, a little bit :D Can you restart this build now?

**Comment by djc** [comment]
Done.

**Comment by djc** [comment]
Still fails:

```
Run actions-rs/tarpaulin@v0.1
  with:
    version: 0.9.0
    args: -- --test-threads 1
##[error]Cannot read property 'find' of undefined
##[error]Node run failed with exit code 1
```

**Comment by svartalf** [comment]
Yeah, it seems that testing should've been done a bit better.
From what I understand from the source code, using specific tarpaulin version is broken, but with `version` input omitted, it should work as expected.

**Comment by svartalf** [comment]
2cad78c0c8951f6aeb2b3193e3ee6e7d9764304e should fix the problem. I'll test it now and re-publish as `v0.1` tag

**Comment by djc** [comment]
Fixed! Thanks.
